### ISSUE TITLE
How to provide this plugin the path of preview thumbnail file?

### ISSUE THREAD

**Issue by hardiklakhalani** [xia-weiyang/image_preview#4]
I've a video URL, how do I show the preview by using this plugin? Do I need to generate thumbnail from another plugin then storing it in local then providing that local path to this preview plugin? Is this the expected method?

**Comment by xia-weiyang** [comment]
The video can be viewed here https://github.com/xia-weiyang/image_preview/blob/4b9d93f1bf864459c70ba71d07b4eb9ffb97692f/lib/preview_data.dart#L85
Currently only the network address or local address of the incoming video thumbnail is supported, and video cover thumbnails cannot be extracted from the video.
